### PR TITLE
Update for staticcheck compliance

### PR DESCRIPTION
**Pull request by geofffranks**
👋Howdy!

We (the App Platform Runtime WG) pull credhub-cli into the  [diego-release](https://github.com/cloudfoundry/diego-release) codebase, and are trying to run [staticcheck](https://staticcheck.dev) on all of its codebases. We found a few things flagged on credhub-cli, and would love it if y'all could incorporate these changes so we don't have to jump through hoops to whitelist certain codebases from our staticcheck automation.

### CODE REVIEW

**Comment by peterhaochen47** [comment]
Hi, thank you! We'll take a look!

But meanwhile, there are 2 test failures from running `make all`:
```
[1709773266] CredHub API Client Suite - 182/182 specs - 15 procs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
------------------------------
• [FAILED] [0.001 seconds]
Client() When a SOCKS5Proxy is set in the environment [It] returns an http.Client with a Dial function
/Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:26

  [FAILED] Expected
      <func(context.Context, string, string) (net.Conn, error)>: nil
  not to be nil
  In [It] at: /Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:33 @ 03/06/24 17:01:24.452
------------------------------
•••••••••••••••••••••••
------------------------------
• [FAILED] [0.002 seconds]
Client() With Dial [It] should return a http.Client with a dial function
/Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:140

  [FAILED] Expected
      <func(context.Context, string, string) (net.Conn, error)>: nil
  not to be nil
  In [It] at: /Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:146 @ 03/06/24 17:01:24.457
------------------------------
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

Summarizing 2 Failures:
  [FAIL] Client() With Dial [It] should return a http.Client with a dial function
  /Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:146
  [FAIL] Client() When a SOCKS5Proxy is set in the environment [It] returns an http.Client with a Dial function
  /Users/peterch/workspace/tmp/credhub-cli/credhub/client_test.go:33

Ran 182 of 182 Specs in 0.064 seconds
FAIL! -- 180 Passed | 2 Failed | 0 Pending | 0 Skipped
```

**Comment by Tallicia** [comment]
Hi @geofffranks Any update on these failures?

**Comment by geofffranks** [comment]
oh, thanks! i missed this comment. Will take a look today.

**Comment by geofffranks** [comment]
Ok, should pass tests now @Tallicia @peterhaochen47 - thanks!

**Review by Tallicia — APPROVED** [review]
Updates for staticCheck look ok

**Pull request merged**
